### ISSUE TITLE
Invalid Date when using drafts

### ISSUE THREAD

**Issue by bernikr** [jekyll/jekyll-sitemap#141]
When I have an undated (neither in the filename nor the frontmatter) draft in the `_drafts` folder, running `jekyll serve --drafts` exits with the following error:

```
    Invalid Date: '' is not a valid datetime.
Liquid Exception: exit in sitemap.xml
```

My current workaround is adding this to my defaults:
```
- scope:
    path: "_drafts"
  values:
    sitemap: false
```

I believe, however, that this should be implemented in jekyll-sitemap to ease the use of drafts.
