### ISSUE TITLE
Sitemap generation conflicts with Jekyll configuration defaults

### ISSUE THREAD

**Issue by kleinfreund** [jekyll/jekyll-sitemap#15]
The following setting in the `_config.yml` leads to the `sitemap.xml` being treated as a page or post and gets `layout: "default"`.

Therefor the content of the sitemap file is wrapped into `default.html` layout.

**_config.yml**

```
defaults:
  -
    scope:
      path: "" # all files have the `default` layout
    values:
      layout: "default"
```

_(Apologies if this isn't a jekyll-sitemap issue, but a jekyll issue. I'm not sure.)_
