### ISSUE TITLE
Bootstrap changelog included in sitemap

### ISSUE THREAD

**Issue by pzp1997** [jekyll/jekyll-sitemap#151]
I have Bootstrap installed on my site via bower. The url `http://my.website.address.com/bower_components/bootstrap/CHANGELOG.html` is included in my sitemap.xml file. Clearly, this is not desirable behavior. Also, I don't want to add `sitemap: false` to the frontmatter because I would prefer to not modify HTML files that are not mine. Is there some way I can exclude the entire bower_components directory from jekyll-sitemap?

**Comment by pathawks** [comment]
Yes, and our documentation should be updated to explain this, as I’m sure that's a pretty common use case.

You’ll need to call the `bower_components` directory a Collection, and then set `sitemap: exclude` as a default for that Collection.

I’ll do a full write-up sometime this week. :+1:

**Comment by benbalter** [comment]
I believe the following should work (without needing a collection):

```yml
defaults:
  -
    scope:
      path: "bower_components/" 
    values:
      sitemap: false
```

**Comment by ambroisemaupate** [comment]
```yaml
defaults:
  - scope:
      path: "bower_components/"
    values:
      sitemap: false
```

Configuration does not work for me.

**Comment by mdrmike** [comment]
I tested on a personal collection, it worked for me.

@ambroisemaupate  look closely at your YAML config syntax... `scope:` should go on the line after `-`

also, I think your `bower_compontents` folder needs to start with underscore (if it isn't already): `_bower_components`



example:
```
defaults:
  -
    scope:
      path: "bower_components/" 
    values:
      sitemap: false
```

**Comment by parkr** [comment]
Static files do not presently obey front matter defaults. We're working on that in https://github.com/jekyll/jekyll/pull/5871.

**Comment by jekyllbot** [comment]
This issue has been automatically marked as stale because it has not been commented on for at least two months.

The resources of the Jekyll team are limited, and so we are asking for your help.

If this is a **bug** and you can still reproduce this error on the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a feature request, please consider whether it can be accomplished in another way. If it cannot, please elaborate on why it is core to this project and why you feel more than 80% of users would find this beneficial.

This issue will automatically be closed in two months if no further activity occurs. Thank you for all your contributions.

**Comment by parkr** [comment]
Static files obey front matter defaults as of 3.4.2.

**Comment by pzp1997** [comment]
I tried what @benbalter suggested, and it does not work for me.

My _config.yml file contains the following defaults:

```
defaults:
  -
    scope:
      path: bower_components/
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
```

The `bower_components/` directory is in the root of my site. What am I missing?
