### ISSUE TITLE
Exclude Pagination Pages

### ISSUE THREAD

**Issue by amalucelli** [jekyll/jekyll-sitemap#163]
Is there any way to exclude pagination pages that are generated by `jekyll-paginate`?

I've already tried to change the order of gems, but didn't worked.

**Comment by pathawks** [comment]
You are right; this is a very common use case.

We should probably take care of this in the **jekyll-paginate** plugin though.

**Comment by fabiomux** [comment]
Yes setting _paginate_path_ as _whatever/:num_ and using Jekyll defaults to assign sitemap to false to the path _whatever_. For instance i used: 
```
paginate_path: blog/page/:num
defaults: 
  - scope:
      path: "blog/page"
    values:
      sitemap: false
```

**Comment by benbalter** [comment]
Should pagination pages be excluded by default?

**Comment by DirtyF** [comment]
> Should pagination pages be excluded by default?

It's not necessary. But adding `prev` and `next` is a plus:
https://support.google.com/webmasters/answer/1663744?hl=en

**Comment by amalucelli** [comment]
Thanks @fabiomux, your example helped me to exclude the pagination pages.

I also couldn't keep the default path that `jekyll-paginate` generates (`/page:num`), because from I could see `path` in `defaults > scope` don't interpret `:num` or any regular expression, so I had to change to `/page/:num`.

My configuration ended like this:

```
paginate: 2
paginate_path: "/page/:num"
defaults:
  -
    scope:
      path: "page"
    values:
      sitemap: false
```

**Comment by mpchadwick** [comment]
Just wanted to leave this note for anyone else who winds up on this thread...front matter defaults work pretty well for this, but depending on your paginate path you may wind up in a scenario where removing paginated URLs also removes your main blog landing page. That is what happened to me, when I was using `paginate_path: "/blog/:num"`, but also had my main blog page at `/blog/`.

In this case you'll need to change your `paginate_path`, but this means that your old paginated URLs will 404. You can solve this by redirecting them with jekyll-redirect-from. I wound up creating a very simple bash script to create all the all redirects

```bash
#!/usr/bin/env bash

count=$1
for ((i=2; i<=count; i++)); do
	mkdir blog/$i
	echo "---" > blog/$i/index.html
	echo "redirect_to: /blog/page/$i" >> blog/$i/index.html
	echo "sitemap: false" >> blog/$i/index.html
	echo "---" >> blog/$i/index.html
done
```

I had 19 paginated URLs at that time, so just run it like this

```
$ ./jekyll-pagination-redirects 19
```

Hope this helps someone. I also did a more detailed write up on this on my blog.

https://maxchadwick.xyz/blog/removing-paginated-urls-from-jekyll-sitemap

**Comment by alvarotrigo** [comment]
Why would we be interested in getting rid of the pagination in the sitemaps.xml? 
We might be using a 10 days cache and we want to tell google to recrawl the page. 

Wouldn't adding a `lastmod` property help google recrawl the URL, which will contain links to new post? 

I'm noticing Google is not updating my page as quick as it should. And that's leasing to articles not being indexed quickly.

**Comment by xRahul** [comment]
Excluding of Pagination pages from page 2 onwards is not working for `jekyll-paginate-v2`.

Path: `posts/page/:num`

Tried:
```
  -
    scope:
      path: "posts/page/*" # "posts/page/*/**" "posts/page/" "posts/page"   
    values:
      sitemap: false
```
Repo: [xRahul.github.io](https://github.com/xRahul/xRahul.github.io)
