### ISSUE TITLE
Binary files do not inherit sitemap: false from defaults

### ISSUE THREAD

**Issue by aterenin** [jekyll/jekyll-sitemap#180]
To reproduce, create a binary file (for example .pdf) somewhere in your Jekyll site and add the following to _config.yml:

```
defaults:
  - scope:
      path: ""
    values:
      sitemap: false
```

Expected behavior: empty sitemap is generated.
Actual behavior: all .md, .html, etc. files are excluded, but binary files with no front matter are included.
