### ISSUE TITLE
Exclude assets demo pages?

### ISSUE THREAD

**Issue by alvarotrigo** [jekyll/jekyll-sitemap#200]
Is there a way to exclude .html files within the assets folder?
Some of them contain some examples and I end up having things like:

```xml
<url>
<loc>https://example.com/blog/assets/vanilla-lazyload/demos/with_picture.html</loc>
<lastmod>2017-11-18T15:05:22+01:00</lastmod>
</url>
```

Where `with_picture.html` is a demo file of a Javascript library, that comes with it when using `npm install` (and I can't be bother to remove those every time for every library)

**Comment by benbalter** [comment]
@alvarotrigo yes. You can do this via [file exclusion](https://github.com/jekyll/jekyll-sitemap#exclusions) and [front matter defaults](https://jekyllrb.com/docs/configuration/#front-matter-defaults).

If you're willing, we'd love your help updating the documentation to make that explicit! :smile:

**Comment by alvarotrigo** [comment]
Could you elaborate your answer and detail how to achieve it? 
Those files are not posts or pages of Jekyll, just files within the assets folder and therefore have no front matter at all. (and not planning to modify them :) )

**Comment by benbalter** [comment]
@alvarotrigo you can set a front-matter default to give those files `sitemap: false` without placing the frontmatter in each file, e.g.:

```yml
defaults:
  - scope:
      path: 'static_files/'
    values:
      sitemap: false
```

**Comment by alvarotrigo** [comment]
Thanks for that! 
I'm trying it but doesn't seem to be working for me?

```
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
  -
    scope:
      path: "assets"
    values:
      sitemap: false 
```

I still get the following kind of entries in the sitemap.xml:
```xml
<url>
<loc>https://alvarotrigo.com/blog/assets/vanilla-lazyload/demos/with_picture.html</loc>
<lastmod>2017-11-18T15:05:22+01:00</lastmod>
</url>
```

**Comment by benbalter** [comment]
@alvarotrigo try adding a trailing slash to `assets/` or spelling out the file in full? See https://github.com/jekyll/jekyll-sitemap/pull/202. I confirmed that HTML files respect YAML front matter defaults. If the above does not resolve your problem, the folks in talk.jekyllrb.com may be able to help as well.

**Comment by alvarotrigo** [comment]
`"assets/"` doesn't work either. 

> or spelling out the file in full? 

Not interested on that. That would be a bit crazy if I have to specify each file for every library I decide to use.

**Comment by morungos** [comment]
I'm having the same issue. 

What's really interesting is that even when I use a scope:

```
defaults:
  - 
    scope:
      path: ""
    values:
      sitemap: false
```

The html files *still* make it into the site map, even though nothing else does. That's with a `keep_files` and an `exclude`. 

The issue is these are generated outside Jekyll, so I can't straightforwardly add front matter to the files. Front matter does work as far as I can tell. 

These files, therefore, somehow manage to bypass the Jekyll defaulting system (I'm testing now with 3.7.0, but 3.4.3 was the same). So it's probably a Jekyll base issue, but not one I am competent to diagnose further.

**Comment by DirtyF** [comment]
@alvarotrigo 

Could you test with jekyll 3.7.0 and jekyll-sitemap 1.2.0 and add a '*' in the path?

```yaml
defaults:
  - scope:
      path: assets/*
    values:
      sitemap: false 
```
