### ISSUE TITLE
Feature: robots.txt allow/disallow

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [jekyll/jekyll-sitemap#209]
Hello Jekyll Community,

Actually, jekyll-sitemap generates robots.txt, but for `Sitemap:`. After that, I realized, why this plugin doesn't have an ability to control robots.txt.

In my mind user edit their `Allow` or `Disallow` with their `_config.yml` file. After that, the sitemap will find this information and it will add to `robots.txt`.

Or, a user can add edit their posts like
```yaml
---
title: Lorem ipsum dolor sit amet
robots-allow: True
---
```

Thank you.
