### ISSUE TITLE
Using global exclusion causes huge CPU hit

### ISSUE THREAD

**Issue by marknelson** [jekyll/jekyll-sitemap#221]
adding the suggested global exclusion  changes the time to generate my site from a few seconds to a few minutes:
```
#
# Exclude from sitemap
#
defaults:
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
```
When I use `assets/**/*` it seems much worse - in fact I'm not sure if it is able to complete. I do see ruby at 100% on top.

With the PDF files I'm trying to exclude I can't put the exclusion in their front matter, this is the only choice.
