### ISSUE TITLE
generating collections in sitemap 3 beta

### ISSUE THREAD

**Issue by justinmusgrove** [jekyll/jekyll-sitemap#80]
It appears that the sitemap plugin isn't generating entries contained within collections folders with the new beta releases. When running a ```jekyll clean``` then a ```jekyll build``` the first file within the _site folder is the sitemap.xml with blog post and pages outside of the collection directories.

Jekyll version: jekyll-3.0.0.pre.beta8
Jekyll version: 0.8.1

Configuration _config.yml:

```
collections:
  groovy-examples:
    output: true

  java-examples:
    output: true

  java-exercises:
    output: true

  java-tutorials:
    output: true

gems:
  - jekyll-paginate
  - jekyll-gist 
  - jekyll-sitemap
```

I verified when switching back to jekyll-2.5.3 it is working, is there something I am missing in the configuration? I don't have mad ruby skills but willing to debug with direction. Thanks
